# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx
r:
  - release
  - devel

branches:
  only:
  - master

r_github_packages:
  - jimhester/covr
r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - ggplot2
  - pbapply
  - testthat
  - roxygen2
  - devtools
  - factorstochvol
  - tinytex

before_install:
  - chmod +x configure
  - chmod +x cleanup

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --ignore-vignettes --no-manual


after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
